---
- hosts: db
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
       - vars/esc_vars.yml
       
  tasks:
    - include: tasks/install_configure_mysql.yml
    
    - include: tasks/pc-db.yml
      when: inventory_hostname == "pc_db-dev"

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
