---

- hosts: test
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars_files:
    - vars/maven_vars.yml
    - vars/github_vars.yml
    - vars/esc_vars.yml
    
  tasks:
    - apt: update_cache=yes
    - name: Create Dev user
      user: name={{ username }} shell=/bin/bash comment="{{ name }}" groups=admin,sudo
    - include: tasks/oracle-jdk8.yml
    - include: tasks/maven.yml
    - include: tasks/github.yml


