---

- name: Install python-pycurl
  apt: 
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pycurl
    - unzip

- name: Configure webupd8team repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Automatically select the Oracle License
  shell: echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | debconf-set-selections

- name: Install Oracle Java 8
  apt: 
    pkg: "oracle-java8-installer"
    state: present
    update_cache: yes
    force: yes

- name: Set the default java version
  apt:
    pkg: "oracle-java8-set-default"
    state: present
    update_cache: yes
    force: yes

# Clean up.
- name: Clean up
  shell: apt-get clean
  
- name: Install JCE Unlimited Strength Jurisdiction Policy Files 8
  copy: 
    src={{ esc_release_dir }}/{{ item }} 
    dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/
  with_items:
    - local_policy.jar
    - US_export_policy.jar
    

  
